name: Release to ZIP

on:
  release:
    types: [created]

jobs:
  zip-release-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create ZIP archive
        id: zip
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          
          ARCHIVE_NAME="${REPO_NAME}-${VERSION}.zip"
          zip -r "$ARCHIVE_NAME" ./*
          
          echo "::set-output name=archive_name::$ARCHIVE_NAME"

      - name: Verify archive existence
        run: |
          ls -lh "${{ steps.zip.outputs.archive_name }}"

      - name: Upload ZIP as release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.zip.outputs.archive_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
